url: https://machongshen.github.io
baseurl: /machongshen_homepage/

# Site settings
title: Chongshen Ma's Studio
email: chongshm@andrew.cmu.edu
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Profile names, titles and social links
people:

- name: Chongshen Ma
  pic: 2
  position: A 2nd-year Master Student in Computer Science
  social:
    - title: twitter
      url: #
    - title: github
      url: # http://github.com/machongshen
    - title: linkedin
      url: # https://www.linkedin.com/in/chongshenma


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty